### ISSUE TITLE
Potential typo at end of airpump_functions.lua - extra space:"vessels:steel_bottle "

### ISSUE THREAD

**Issue by sirrobzeroone** [mt-mods/vacuum#22]
Might be deliberate?, I cant test easily as I have my version of vacuum on my computer in pieces but I think this line

https://github.com/mt-mods/vacuum/blob/0380b279ea104a5f771562a26c109bcbaf2e1de7/airpump_functions.lua#L112

has an extra space in "vessels:steel_bottle " and should be "vessels:steel_bottle"

Happy for this to be closed if it's deliberate just wanted to flag it in case it was a mistake - found trying to do a find/replace

**Comment by BuckarooBanzay** [comment]
Thanks for the report but this is deliberate:
The `vacuum.flush_bottle_usage` variable contains the amount of the bottles added to the inventory, this would resolve to something like this for example: "vessels:steel_bottle 99"
Without the space between it would be an invalid item :yum: 

Feel free to open another issue if you find something :+1:

**Comment by sirrobzeroone** [comment]
lol i see.....couldnt see the wood for the trees so to speak.....
